### PR TITLE
Maintain authentication when making paginated .prev/.next requests

### LINKED ISSUE #325: Fetching posts not authenticating properly.
I commented on the issue [here](https://github.com/WP-API/node-wpapi/issues/154#issuecomment-312186212) and even posted the issue on [SO](https://stackoverflow.com/questions/44840350/fetching-drafts-forbidden-in-wordpress-rest-api) but now I'm opening a new issue to try and figure this out.

I've tried nearly every convocation of fetching drafts. My primary site constructor is using Basic Auth and works to fetch/create/delete posts. It even created the draft posts in questions.

When I go to fetch, I get this error:

```javascript
{ code: 'rest_invalid_param',
  message: 'Invalid parameter(s): status',
  data: { status: 400, params: { status: 'Status is forbidden.' } } }
```

I've used these various methods for trying to fetch drafts:

```javascript
wp.posts().auth().param( 'context', 'edit' ).param('status', 'draft')
wp.posts().auth({
  username: process.env.WP_USER,
  password: process.env.WP_PASSWORD
}).param('status','draft')
```

as well as various versions with `.status('draft')`, `.param({status: 'draft'})` as well as removing the `.auth()` method chaining, etc.

After some further attempts I was able to fetch the drafts by bypassing the library all-together and using request. Further, I was able to fetch the posts normally by swapping out `draft` with `publish` and that returns the public posts. This leads me to the assumptions:
1. My authentication is correct.
2. There's a bug somewhere in the library's auth mechanism.

Thanks for any help on this!

### PR DESCRIPTION
**Pull request by kadamwhite**
When we create the WPRequest object to handle the previous or next pages of a collection (when available), we were passing only the endpoint and the HTTP Transport object -- this creates a valid WPRequest object, but authentication parameters are then not passed on to the new request objects. This PR updates the logic within the transport to maintain any set options on the request, overwriting only the endpoint URI, so that authentication will be maintained when paging through a collection.

Fixes #325 
props @motleydev

### CODE REVIEW

File: lib/data/update-default-routes-json.js [hunk 1]
```diff
@@ -81,6 +81,9 @@ var outputPath = argv.output ?
 // Specify your own API endpoint with --endpoint=http://your-endpoint.com/wp-json
 var endpoint = argv.endpoint || 'http://wpapi.loc/wp-json';
 
+// Specify a custom output file name with --file=custom-api-routes-filename.json
+var fileName = argv.file || 'default-routes.json';
```
Comment (kadamwhite) [inline lib/data/update-default-routes-json.js]: Eh, this is an unrelated change, will rebase it out for cleanliness
